all: ShinyCounter
ShinyCounter: ShinyCounter.java Counter.java
	javac ShinyCounter.java
run: ShinyCounter.class Counter.class
	java ShinyCounter
clean:
	/bin/rm ShinyCounter.class
	/bin/rm Counter.class
